services:
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: devops-ic-redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db:
  redis:
